from __future__ import annotations

from pathlib import Path
from typing import Any, Dict, Iterable


class StaticSiteGenerator:
    def __init__(
        self,
        project_name: str,
        output_base_dir: str,
        brief: Dict[str, Any] | None = None,
        description: str = "",
        style: str = "",
        language: str = "pt-BR",
        automation: Dict[str, Any] | None = None,
        integrations: Dict[str, Any] | None = None,
        **kwargs: Any,
    ) -> None:
        self.project_name = project_name
        self.output_base_dir = Path(output_base_dir)
        self.brief = dict(brief or {})
        self.description = description or str(self.brief.get("project_description") or self.brief.get("business_goal") or "")
        self.style = style or str(self.brief.get("visual_style") or "premium")
        self.language = language or str(self.brief.get("language") or "pt-BR")
        self.automation = dict(automation or {})
        self.integrations = dict(integrations or {})
        self.extra = dict(kwargs)

    def _section_slug(self, value: str) -> str:
        return value.strip().lower().replace(" ", "-").replace("_", "-")

    def _sections(self) -> list[str]:
        sections = self.brief.get("sections")
        if isinstance(sections, list) and sections:
            return [str(item).strip() for item in sections if str(item).strip()]
        return ["hero", "about", "services", "contact"]

    def _html_section(self, section: str) -> str:
        title = section.replace("-", " ").title()
        if section == "hero":
            return f"<section class=\"hero\"><h1>{self.project_name}</h1><p>{self.description or 'A premium static site generated by SaaS Factory AI.'}</p><a class=\"cta\" href=\"#contact\">Get in touch</a></section>"
        if section == "contact":
            return "<section id=\"contact\"><h2>Contact</h2><form><input type=\"text\" placeholder=\"Your name\" /><input type=\"email\" placeholder=\"Email\" /><textarea placeholder=\"Message\"></textarea><button type=\"submit\">Send</button></form></section>"
        if section == "faq":
            return "<section><h2>FAQ</h2><details><summary>How does it work?</summary><p>Built with semantic HTML, CSS and JS.</p></details></section>"
        if section == "services":
            return "<section><h2>Services</h2><ul><li>Discovery</li><li>Design</li><li>Launch</li></ul></section>"
        if section == "about":
            return "<section><h2>About</h2><p>Focused on clarity, conversion and performance.</p></section>"
        return f"<section><h2>{title}</h2><p>Section generated for {title}.</p></section>"

    def _index_html(self, sections: Iterable[str]) -> str:
        section_markup = "\n      ".join(self._html_section(section) for section in sections)
        meta_title = self.brief.get("seo_title") or self.project_name
        meta_description = self.brief.get("seo_description") or self.description or self.project_name
        return f"""<!doctype html>
<html lang=\"{self.language}\">
  <head>
    <meta charset=\"utf-8\" />
    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />
    <title>{meta_title}</title>
    <meta name=\"description\" content=\"{meta_description}\" />
    <meta property=\"og:title\" content=\"{self.brief.get('open_graph_title') or meta_title}\" />
    <meta property=\"og:description\" content=\"{self.brief.get('open_graph_description') or meta_description}\" />
    <link rel=\"stylesheet\" href=\"assets/css/style.css\" />
  </head>
  <body class=\"theme-{self._section_slug(self.style)}\">
    <main>
      {section_markup}
    </main>
    <script src=\"assets/js/main.js\"></script>
  </body>
</html>
"""

    def _write_file(self, path: Path, content: str) -> None:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")

    def generate(self) -> str:
        self.output_base_dir.mkdir(parents=True, exist_ok=True)
        project_root = self.output_base_dir
        sections = self._sections()

        assets_css = project_root / "assets" / "css" / "style.css"
        assets_js = project_root / "assets" / "js" / "main.js"
        docs_dir = project_root / "docs"

        self._write_file(
            project_root / "index.html",
            self._index_html(sections),
        )
        self._write_file(
            assets_css,
            """html,body{margin:0;padding:0;font-family:system-ui,-apple-system,Segoe UI,Roboto,sans-serif;background:#0a0f1a;color:#eaf0ff}main{max-width:1100px;margin:0 auto;padding:48px 20px;display:grid;gap:24px}section{background:rgba(255,255,255,.04);border:1px solid rgba(255,255,255,.08);border-radius:24px;padding:24px;backdrop-filter:blur(20px)}.hero{padding:48px}.cta{display:inline-block;margin-top:16px;padding:12px 18px;border-radius:999px;background:linear-gradient(135deg,#67e8f9,#8b5cf6);color:#08101f;text-decoration:none;font-weight:700}form{display:grid;gap:12px}input,textarea,button{border-radius:14px;border:1px solid rgba(255,255,255,.12);padding:12px 14px;background:rgba(255,255,255,.04);color:inherit}button{background:linear-gradient(135deg,#67e8f9,#8b5cf6);color:#08101f;font-weight:700;cursor:pointer}""",
        )
        self._write_file(assets_js, "document.addEventListener('DOMContentLoaded',()=>console.log('Static Site ready'));")
        self._write_file(project_root / "README.md", f"# {self.project_name}\n\nGenerated static site for {self.description or self.project_name}.\n")
        self._write_file(docs_dir / "SEO.md", "# SEO\n\n- Meta title and description configured.\n- Open Graph tags included.\n")
        self._write_file(docs_dir / "ACCESSIBILITY.md", "# Accessibility\n\n- Semantic HTML used.\n- Responsive layout.\n- Reduced motion friendly.\n")
        self._write_file(docs_dir / "PROMPT_MASTER.md", f"# Prompt Master\n\n{self.description or self.project_name}\n")

        for section in sections:
            self._write_file(project_root / "sections" / f"{self._section_slug(section)}.html", self._html_section(section))

        return str(project_root)
