IMPLEMENTED_STACKS = {
    "spring_boot": {"status": "stable"},
    "fastapi": {"status": "stable"},
    "nestjs": {"status": "stable"},
    "express": {"status": "stable"},
    "laravel": {"status": "partial"},
    "dotnet": {"status": "partial"},
    "angular": {"status": "stable"},
    "react": {"status": "stable"},
    "nextjs": {"status": "stable"},
    "vue": {"status": "stable"},
    "blazor": {"status": "stable"},
    "automation": {"status": "stable"},
    "ai_agents": {"status": "stable"},
    "static_site": {"status": "stable"},
    "grpc": {"status": "planned"},
}
