STACK_PROFILES = {
    "spring_boot": {
        "id": "spring_boot",
        "name": "Java + Spring Boot",
        "category": "backend",
        "status": "stable",
        "allowed_databases": ["PostgreSQL", "MySQL", "H2", "Oracle"],
        "allowed_auth": ["JWT", "OAuth2", "Keycloak", "Session"],
        "allowed_architecture": ["monolith", "modular_monolith", "microservices", "event_driven"],
        "allowed_testing": ["JUnit", "Mockito", "Testcontainers"],
        "allowed_messaging": ["Kafka", "RabbitMQ", "Redis", "SSE", "WebSocket"],
        "recommended_frontends": ["Angular", "React", "Vue", "Thymeleaf"],
        "recommended_backends": ["Spring Boot"],
        "required_files": ["pom.xml", "src/main/java", "src/test/java", "src/main/resources", "README.md"],
        "forbidden_terms": ["FastAPI", "Pydantic", "Uvicorn", "SQLAlchemy", "Laravel Sanctum", "Blazor"],
        "supported_architectures": ["monolith", "modular_monolith", "microservices", "event_driven"],
        "default_versions": {"java_version": "21", "spring_boot_version": "3.3.x", "build_tool": "maven"},
    },
    "fastapi": {
        "id": "fastapi",
        "name": "Python + FastAPI",
        "category": "backend",
        "status": "stable",
        "allowed_databases": ["PostgreSQL", "MySQL", "SQLite"],
        "allowed_auth": ["JWT", "OAuth2"],
        "allowed_architecture": ["modular_api", "layered", "clean_architecture"],
        "allowed_testing": ["Pytest", "HTTPX", "AsyncIO"],
        "allowed_messaging": ["Kafka", "RabbitMQ", "Redis", "WebSocket", "SSE"],
        "recommended_frontends": ["React", "Next.js", "Vue"],
        "recommended_backends": ["FastAPI"],
        "required_files": ["app", "tests", "README.md", "requirements.txt"],
        "forbidden_terms": ["Spring Security", "Eureka", "Maven", "Gradle", "Laravel Blade"],
        "supported_architectures": ["modular_api", "layered", "clean_architecture"],
        "default_versions": {"python_version": "3.12", "orm": "sqlalchemy", "database": "postgresql"},
    },
    "nestjs": {
        "id": "nestjs",
        "name": "Node.js + NestJS",
        "category": "backend",
        "status": "stable",
        "allowed_databases": ["PostgreSQL", "MySQL", "MongoDB"],
        "allowed_auth": ["JWT", "Passport", "OAuth2"],
        "allowed_architecture": ["modular", "microservices"],
        "allowed_testing": ["Jest", "Supertest"],
        "allowed_messaging": ["Kafka", "RabbitMQ", "Redis", "WebSocket"],
        "recommended_frontends": ["Angular", "React", "Next.js"],
        "recommended_backends": ["NestJS"],
        "required_files": ["src", "test", "README.md", "package.json"],
        "forbidden_terms": ["Pom.xml", "requirements.txt", "Spring", "FastAPI", "Laravel"],
        "supported_architectures": ["modular", "microservices"],
        "default_versions": {"node_version": "20", "typescript_version": "5.4", "orm": "prisma"},
    },
    "express": {
        "id": "express",
        "name": "Node.js + Express",
        "category": "backend",
        "status": "stable",
        "allowed_databases": ["PostgreSQL", "MySQL", "MongoDB"],
        "allowed_auth": ["JWT", "Passport"],
        "allowed_architecture": ["simple_api", "modular_api"],
        "allowed_testing": ["Jest", "Supertest"],
        "allowed_messaging": ["Redis", "WebSocket", "SSE"],
        "recommended_frontends": ["React", "Vue", "Next.js"],
        "recommended_backends": ["Express"],
        "required_files": ["src", "test", "README.md", "package.json"],
        "forbidden_terms": ["Pom.xml", "requirements.txt", "Spring", "NestJS", "Laravel"],
        "supported_architectures": ["simple_api", "modular_api"],
        "default_versions": {"node_version": "20", "orm": "prisma"},
    },
    "laravel": {
        "id": "laravel",
        "name": "PHP + Laravel",
        "category": "backend",
        "status": "partial",
        "allowed_databases": ["MySQL", "PostgreSQL", "SQLite"],
        "allowed_auth": ["Sanctum", "Passport", "None"],
        "allowed_architecture": ["mvc", "modular"],
        "allowed_testing": ["Pest", "PHPUnit"],
        "allowed_messaging": ["Redis", "RabbitMQ", "WebSocket"],
        "recommended_frontends": ["Blade", "Vue", "React", "Inertia"],
        "recommended_backends": ["Laravel"],
        "required_files": ["app", "routes", "tests", "README.md", "composer.json"],
        "forbidden_terms": ["Pom.xml", "requirements.txt", "Spring", "FastAPI", "NestJS"],
        "supported_architectures": ["mvc", "modular"],
        "default_versions": {"php_version": "8.3", "laravel_version": "11", "queues": "redis"},
    },
    "dotnet": {
        "id": "dotnet",
        "name": "C# + ASP.NET Core",
        "category": "backend",
        "status": "partial",
        "allowed_databases": ["SQL Server", "PostgreSQL", "SQLite"],
        "allowed_auth": ["Identity", "JWT", "OAuth2"],
        "allowed_architecture": ["minimal_api", "clean_architecture", "modular_monolith"],
        "allowed_testing": ["xUnit", "NUnit", "MSTest"],
        "allowed_messaging": ["RabbitMQ", "Redis", "WebSocket", "SSE"],
        "recommended_frontends": ["Blazor", "Angular", "React"],
        "recommended_backends": ["ASP.NET Core"],
        "required_files": ["src", "tests", "README.md", "*.csproj"],
        "forbidden_terms": ["Pom.xml", "requirements.txt", "Spring", "FastAPI", "NestJS", "Laravel"],
        "supported_architectures": ["minimal_api", "clean_architecture", "modular_monolith"],
        "default_versions": {"dotnet_version": "8.0", "swagger": True, "hosting_model": "server"},
    },
    "static": {
        "id": "static",
        "name": "Static Site",
        "category": "frontend",
        "status": "stable",
        "allowed_databases": ["Nenhum"],
        "allowed_auth": ["Nenhum"],
        "allowed_architecture": ["static", "seo_first"],
        "allowed_testing": ["Playwright", "Lighthouse"],
        "allowed_messaging": ["Nenhum"],
        "recommended_frontends": ["HTML/CSS/JS", "Next.js"],
        "recommended_backends": ["Nenhum"],
        "required_files": ["index.html", "assets/css/style.css", "assets/js/main.js", "README.md"],
        "forbidden_terms": ["Spring", "FastAPI", "JWT", "database", "backend"],
        "supported_architectures": ["static", "seo_first"],
        "default_versions": {"html": "5", "css": "3", "javascript": "es2023"},
    },
    "angular": {
        "id": "angular",
        "name": "Angular",
        "category": "frontend",
        "status": "stable",
        "allowed_databases": ["None"],
        "allowed_auth": ["JWT", "OAuth2", "None"],
        "allowed_architecture": ["spa", "enterprise_frontend"],
        "allowed_testing": ["Jest", "Karma", "Cypress"],
        "allowed_messaging": ["None"],
        "recommended_frontends": ["Angular"],
        "recommended_backends": ["Spring Boot", "NestJS"],
        "required_files": ["src", "angular.json", "README.md", "package.json"],
        "forbidden_terms": ["pom.xml", "requirements.txt", "FastAPI", "Spring Boot", "Laravel"],
        "supported_architectures": ["spa", "enterprise_frontend"],
        "default_versions": {"angular_version": "18", "node_version": "20", "state_management": "ngrx"},
    },
    "react": {
        "id": "react",
        "name": "React",
        "category": "frontend",
        "status": "stable",
        "allowed_databases": ["None"],
        "allowed_auth": ["JWT", "OAuth2", "None"],
        "allowed_architecture": ["spa", "frontend_platform"],
        "allowed_testing": ["Vitest", "Jest", "Playwright"],
        "allowed_messaging": ["None"],
        "recommended_frontends": ["React"],
        "recommended_backends": ["FastAPI", "Express", "Spring Boot"],
        "required_files": ["src", "README.md", "package.json"],
        "forbidden_terms": ["pom.xml", "requirements.txt", "Spring Boot", "FastAPI"],
        "supported_architectures": ["spa", "frontend_platform"],
        "default_versions": {"react_version": "18", "node_version": "20", "state_management": "zustand"},
    },
    "nextjs": {
        "id": "nextjs",
        "name": "Next.js",
        "category": "frontend",
        "status": "stable",
        "allowed_databases": ["None", "PostgreSQL", "MySQL"],
        "allowed_auth": ["JWT", "NextAuth", "OAuth2", "None"],
        "allowed_architecture": ["ssr", "ssg", "isr", "csr"],
        "allowed_testing": ["Playwright", "Vitest", "Jest"],
        "allowed_messaging": ["None"],
        "recommended_frontends": ["Next.js"],
        "recommended_backends": ["FastAPI", "NestJS"],
        "required_files": ["app", "src", "README.md", "package.json"],
        "forbidden_terms": ["pom.xml", "requirements.txt", "Spring Boot"],
        "supported_architectures": ["ssr", "ssg", "isr", "csr"],
        "default_versions": {"nextjs_version": "14", "react_version": "18", "node_version": "20"},
    },
    "vue": {
        "id": "vue",
        "name": "Vue",
        "category": "frontend",
        "status": "stable",
        "allowed_databases": ["None"],
        "allowed_auth": ["JWT", "OAuth2", "None"],
        "allowed_architecture": ["spa", "frontend_platform"],
        "allowed_testing": ["Vitest", "Cypress"],
        "allowed_messaging": ["None"],
        "recommended_frontends": ["Vue"],
        "recommended_backends": ["Laravel", "FastAPI", "Express"],
        "required_files": ["src", "README.md", "package.json"],
        "forbidden_terms": ["pom.xml", "requirements.txt", "Spring Boot"],
        "supported_architectures": ["spa", "frontend_platform"],
        "default_versions": {"vue_version": "3", "node_version": "20", "state_management": "pinia"},
    },
    "blazor": {
        "id": "blazor",
        "name": "Blazor",
        "category": "frontend",
        "status": "stable",
        "allowed_databases": ["None"],
        "allowed_auth": ["Identity", "JWT", "None"],
        "allowed_architecture": ["server", "wasm"],
        "allowed_testing": ["bUnit", "Playwright"],
        "allowed_messaging": ["SignalR"],
        "recommended_frontends": ["Blazor"],
        "recommended_backends": ["ASP.NET Core"],
        "required_files": ["Pages", "Shared", "README.md", "*.csproj"],
        "forbidden_terms": ["requirements.txt", "pom.xml", "Spring Boot", "FastAPI"],
        "supported_architectures": ["server", "wasm"],
        "default_versions": {"dotnet_version": "8.0", "hosting_model": "server"},
    },
    "automation": {
        "id": "automation",
        "name": "Automation",
        "category": "automation",
        "status": "stable",
        "allowed_databases": ["PostgreSQL", "MySQL", "Redis", "None"],
        "allowed_auth": ["JWT", "OAuth2", "None"],
        "allowed_architecture": ["workflow", "event_driven", "scheduled"],
        "allowed_testing": ["Pytest", "Jest"],
        "allowed_messaging": ["Redis", "RabbitMQ", "Kafka"],
        "recommended_frontends": ["React", "Next.js", "Angular"],
        "recommended_backends": ["FastAPI", "NestJS", "Spring Boot"],
        "required_files": ["workflows", "integrations", "README.md", "generation_trace.json"],
        "forbidden_terms": ["hardcoded_secrets", "no_logs", "unsafe_tools"],
        "supported_architectures": ["workflow", "event_driven", "scheduled"],
        "default_versions": {"queue": "redis", "schedule": "cron", "retries": True},
    },
    "ai_agents": {
        "id": "ai_agents",
        "name": "AI Agents",
        "category": "ai",
        "status": "stable",
        "allowed_databases": ["None", "PostgreSQL", "Vector DB"],
        "allowed_auth": ["JWT", "OAuth2", "None"],
        "allowed_architecture": ["single_agent", "multi_agent", "orchestrated"],
        "allowed_testing": ["Pytest", "Eval Harness"],
        "allowed_messaging": ["Queue", "Redis", "WebSocket"],
        "recommended_frontends": ["React", "Next.js"],
        "recommended_backends": ["FastAPI", "NestJS", "Spring Boot"],
        "required_files": ["agents", "tools", "README.md", "generation_trace.json"],
        "forbidden_terms": ["hardcoded_api_key", "no_guardrails", "no_logs", "unsafe_tooling"],
        "supported_architectures": ["single_agent", "multi_agent", "orchestrated"],
        "default_versions": {"llm_provider": "openai", "memory": "vector_db", "tests": "pytest"},
    },
}
