STACK_PROFILES = {
    "springboot": {
        "backend": "Java + Spring Boot",
        "frontends": ["Angular", "React", "Vue", "Thymeleaf"],
        "databases": ["PostgreSQL", "MySQL", "H2"],
        "security": ["Spring Security", "JWT", "OAuth2", "Keycloak"],
        "messaging": ["Kafka", "RabbitMQ", "Redis", "WebSocket", "SSE"],
        "forbidden_terms": ["FastAPI", "Pydantic", "Uvicorn", "SQLAlchemy", "Laravel Sanctum", "Blazor"],
    },
    "fastapi": {
        "backend": "Python + FastAPI",
        "frontends": ["React", "Next.js", "Vue"],
        "databases": ["PostgreSQL", "MySQL", "SQLite"],
        "security": ["JWT", "OAuth2"],
        "messaging": ["Kafka", "RabbitMQ", "Redis", "WebSocket", "SSE"],
        "forbidden_terms": ["Spring Security", "Eureka", "Maven", "Gradle", "Laravel Blade"],
    },
    "nestjs": {
        "backend": "Node.js + NestJS",
        "frontends": ["Angular", "React", "Next.js"],
        "databases": ["PostgreSQL", "MySQL", "MongoDB"],
        "security": ["JWT", "Passport", "OAuth2"],
        "messaging": ["Kafka", "RabbitMQ", "Redis", "WebSocket"],
        "forbidden_terms": ["Pom.xml", "requirements.txt", "Spring", "FastAPI", "Laravel"],
    },
    "express": {
        "backend": "Node.js + Express",
        "frontends": ["React", "Vue", "Next.js"],
        "databases": ["PostgreSQL", "MySQL", "MongoDB"],
        "security": ["JWT", "Passport"],
        "messaging": ["Redis", "WebSocket", "SSE"],
        "forbidden_terms": ["Pom.xml", "requirements.txt", "Spring", "NestJS", "Laravel"],
    },
    "laravel": {
        "backend": "PHP + Laravel",
        "frontends": ["Blade", "Vue", "React", "Inertia"],
        "databases": ["MySQL", "PostgreSQL", "SQLite"],
        "security": ["Sanctum", "Passport"],
        "messaging": ["Redis", "RabbitMQ", "WebSocket"],
        "forbidden_terms": ["Pom.xml", "requirements.txt", "package.json", "Spring", "FastAPI", "NestJS"],
    },
    "dotnet": {
        "backend": "C# + ASP.NET Core",
        "frontends": ["Blazor", "Angular", "React"],
        "databases": ["SQL Server", "PostgreSQL", "SQLite"],
        "security": ["Identity", "JWT", "OAuth2"],
        "messaging": ["RabbitMQ", "Redis", "WebSocket", "SSE"],
        "forbidden_terms": ["Pom.xml", "requirements.txt", "package.json", "Spring", "FastAPI", "NestJS", "Laravel"],
    },
    "static": {
        "backend": "Static Site",
        "frontends": ["HTML/CSS/JS", "Next.js (SSG)"],
        "databases": ["Nenhum"],
        "security": ["Nenhum"],
        "messaging": ["SSE"],
        "forbidden_terms": ["Pom.xml", "requirements.txt", "Spring", "FastAPI", "JWT", "backend", "database"],
    },
    # Frontend stacks
    "angular": {
        "backend": "Angular",
        "frontends": ["Angular"],
        "databases": ["Nenhum"],
        "security": ["JWT", "OAuth2"],
        "messaging": ["None"],
        "forbidden_terms": ["pom.xml", "requirements.txt", "FastAPI", "Spring Boot", "Laravel"],
        "recommended_backends": ["Spring Boot", "NestJS"],
    },
    "react": {
        "backend": "React",
        "frontends": ["React"],
        "databases": ["Nenhum"],
        "security": ["JWT", "OAuth2"],
        "messaging": ["None"],
        "forbidden_terms": ["pom.xml", "requirements.txt", "Spring Boot"],
        "recommended_backends": ["FastAPI", "Express", "Spring Boot"],
    },
    "nextjs": {
        "backend": "Next.js",
        "frontends": ["Next.js"],
        "databases": ["Nenhum"],
        "security": ["JWT", "NextAuth"],
        "messaging": ["None"],
        "forbidden_terms": ["pom.xml", "requirements.txt", "Spring Boot"],
        "recommended_backends": ["FastAPI", "NestJS"],
    },
    "vue": {
        "backend": "Vue",
        "frontends": ["Vue"],
        "databases": ["Nenhum"],
        "security": ["JWT", "OAuth2"],
        "messaging": ["None"],
        "forbidden_terms": ["pom.xml", "requirements.txt", "Spring Boot"],
        "recommended_backends": ["Laravel", "FastAPI", "Express"],
    },
    "blazor": {
        "backend": "Blazor",
        "frontends": ["Blazor"],
        "databases": ["Nenhum"],
        "security": ["Identity", "JWT"],
        "messaging": ["SignalR"],
        "forbidden_terms": ["pom.xml", "requirements.txt", "FastAPI", "Spring Boot", "Laravel"],
        "recommended_backends": ["ASP.NET Core"],
    },
}
