from __future__ import annotations

import json
import os
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, Iterable

from stack_registry.registry import StackRegistry


def _safe_name(value: str) -> str:
    return "".join(ch.lower() if ch.isalnum() else "_" for ch in str(value or "generated")).strip("_") or "generated"


def _write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def _blueprint_dict(blueprint: Any) -> Dict[str, Any]:
    if hasattr(blueprint, "model_dump"):
        return blueprint.model_dump()
    if isinstance(blueprint, dict):
        return dict(blueprint)
    return {}


def _entities(blueprint: Dict[str, Any]) -> list[str]:
    raw = blueprint.get("confirmed_entities") or blueprint.get("entities") or ["Resource"]
    result: list[str] = []
    for item in raw:
        if isinstance(item, dict):
            name = item.get("name") or item.get("original_name")
        else:
            name = str(item)
        name = "".join(ch for ch in str(name or "Resource") if ch.isalnum()) or "Resource"
        result.append(name)
    return result or ["Resource"]


@dataclass
class BackendValidator:
    stack_id: str
    backend_path: str

    def run_all(self) -> Dict[str, Any]:
        registry = StackRegistry()
        canonical = registry.normalize_stack_id(self.stack_id)
        try:
            stack = registry.get_stack(canonical)
        except ValueError as exc:
            return {"status": "failed", "errors": [str(exc)], "checks": []}

        missing = []
        for rel in stack.get("required_files", []):
            if "*" in rel:
                continue
            if not (Path(self.backend_path) / rel).exists():
                missing.append(rel)

        return {
            "status": "failed" if missing else "passed",
            "stack_id": canonical,
            "backend_path": self.backend_path,
            "checks": [{"required_files": stack.get("required_files", []), "missing": missing}],
            "errors": [f"Missing required file: {item}" for item in missing],
        }


class ScaffoldBackendGenerator:
    def __init__(self, stack_id: str, blueprint: Any, output_path: str):
        self.registry = StackRegistry()
        self.stack_id = self.registry.normalize_stack_id(stack_id)
        self.blueprint = _blueprint_dict(blueprint)
        self.output_path = Path(output_path)

    def generate(self) -> str:
        project_root = self._resolve_project_root()
        project_root.mkdir(parents=True, exist_ok=True)
        self._write_common(project_root)

        if self.stack_id == "spring_boot":
            self._spring_boot(project_root)
        elif self.stack_id == "fastapi":
            self._fastapi(project_root)
        elif self.stack_id in {"nestjs", "express"}:
            self._node_api(project_root, framework=self.stack_id)
        elif self.stack_id == "laravel":
            self._laravel(project_root)
        elif self.stack_id == "dotnet":
            self._dotnet(project_root)
        elif self.stack_id in {"angular", "react", "nextjs", "vue", "blazor"}:
            self._frontend(project_root, framework=self.stack_id)
        elif self.stack_id == "automation":
            self._automation(project_root)
        elif self.stack_id == "ai_agents":
            self._ai_agents(project_root)
        else:
            self._generic(project_root)

        _write(project_root / "generation_trace_data.json", json.dumps({
            "generator": "ScaffoldBackendGenerator",
            "stack_id": self.stack_id,
            "quality": "deterministic_scaffold",
        }, indent=2))
        return str(project_root)

    def _resolve_project_root(self) -> Path:
        if self.output_path.name and self.output_path.parent.name == "generated_projects":
            return self.output_path
        project_name = _safe_name(self.blueprint.get("project_name", "generated_project"))
        return self.output_path / project_name

    def _write_common(self, root: Path) -> None:
        _write(root / "README.md", f"# {self.blueprint.get('project_name', 'Generated Project')}\n\nStack: {self.stack_id}\n\nGenerated by SaaS Factory AI official pipeline.\n")
        _write(root / "docs" / "ARCHITECTURE.md", json.dumps({
            "stack": self.stack_id,
            "architecture": self.blueprint.get("architecture"),
            "entities": _entities(self.blueprint),
        }, indent=2))
        _write(root / ".env.example", "APP_ENV=local\nDATABASE_URL=postgresql://user:password@localhost:5432/app\nJWT_SECRET=change_me\n")
        _write(root / ".gitignore", ".env\nnode_modules/\n__pycache__/\ntarget/\nbin/\nobj/\n")

    def _spring_boot(self, root: Path) -> None:
        java_version = str(self.blueprint.get("java_version") or "21")
        package = "com.saasfactory.generated"
        _write(root / "pom.xml", f"""<project xmlns="http://maven.apache.org/POM/4.0.0">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.saasfactory</groupId>
  <artifactId>generated-service</artifactId>
  <version>0.1.0</version>
  <properties><java.version>{java_version}</java.version><spring-boot.version>3.3.0</spring-boot.version></properties>
</project>
""")
        _write(root / "src" / "main" / "java" / "com" / "saasfactory" / "generated" / "Application.java", f"""package {package};

public class Application {{
  public static void main(String[] args) {{
    // Spring Boot entrypoint scaffold.
  }}
}}
""")
        _write(root / "src" / "main" / "resources" / "application.yml", "spring:\n  application:\n    name: generated-service\n")
        _write(root / "src" / "test" / "java" / "com" / "saasfactory" / "generated" / "ApplicationTest.java", "package com.saasfactory.generated;\n\nclass ApplicationTest {}\n")

    def _fastapi(self, root: Path) -> None:
        _write(root / "requirements.txt", "fastapi==0.111.0\nuvicorn==0.30.1\npydantic>=2.9.2\npytest==8.2.2\n")
        _write(root / "app" / "main.py", '''from fastapi import FastAPI

app = FastAPI(title="Generated API", openapi_url="/openapi.json")


@app.get("/health")
def health():
    return {"status": "ok"}
''')
        _write(root / "app" / "__init__.py", "")
        _write(root / "tests" / "test_health.py", "from app.main import health\n\n\ndef test_health():\n    assert health()[\"status\"] == \"ok\"\n")

    def _node_api(self, root: Path, framework: str) -> None:
        deps = {"nestjs": "@nestjs/core", "express": "express"}
        _write(root / "package.json", json.dumps({
            "name": f"generated-{framework}",
            "version": "0.1.0",
            "scripts": {"test": "echo \"tests pending\"", "start": "node src/main.js"},
            "dependencies": {deps[framework]: "latest", "swagger-ui-express": "latest"},
            "devDependencies": {"typescript": "^5.0.0"},
        }, indent=2))
        _write(root / "src" / "main.js", "const openapi = { title: 'Generated API' };\nconsole.info(openapi.title);\n")
        _write(root / "test" / "health.test.js", "test('health scaffold', () => expect(true).toBe(true));\n")

    def _laravel(self, root: Path) -> None:
        _write(root / "composer.json", json.dumps({"require": {"php": "^8.3", "laravel/framework": "^11.0"}}, indent=2))
        _write(root / "app" / "Http" / "Controllers" / "HealthController.php", "<?php\nclass HealthController { public function __invoke() { return ['status' => 'ok']; } }\n")
        _write(root / "routes" / "api.php", "<?php\n// Route::get('/health', HealthController::class);\n")
        _write(root / "tests" / "Feature" / "HealthTest.php", "<?php\n// health test scaffold\n")

    def _dotnet(self, root: Path) -> None:
        _write(root / "src" / "Generated.Api" / "Generated.Api.csproj", '<Project Sdk="Microsoft.NET.Sdk.Web"><PropertyGroup><TargetFramework>net8.0</TargetFramework></PropertyGroup></Project>\n')
        _write(root / "src" / "Generated.Api" / "Program.cs", "var builder = WebApplication.CreateBuilder(args);\nbuilder.Services.AddEndpointsApiExplorer();\nvar app = builder.Build();\napp.MapGet(\"/health\", () => new { status = \"ok\" });\napp.Run();\n")
        _write(root / "tests" / "Generated.Tests" / "Generated.Tests.csproj", '<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><TargetFramework>net8.0</TargetFramework></PropertyGroup></Project>\n')

    def _frontend(self, root: Path, framework: str) -> None:
        _write(root / "package.json", json.dumps({
            "name": f"generated-{framework}",
            "version": "0.1.0",
            "scripts": {"build": "echo build", "test": "echo test"},
            "dependencies": {framework if framework != "nextjs" else "next": "latest"},
        }, indent=2))
        src_dir = "app" if framework == "nextjs" else "src"
        _write(root / src_dir / "page.tsx", "export default function Page() { return <main>Generated responsive page</main>; }\n")
        if framework == "angular":
            _write(root / "angular.json", "{}\n")
        if framework == "blazor":
            _write(root / "Generated.Blazor.csproj", '<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly"></Project>\n')

    def _automation(self, root: Path) -> None:
        _write(root / "workflows" / "main.workflow.json", json.dumps({"steps": ["validate", "execute", "retry", "report"]}, indent=2))
        _write(root / "integrations" / "README.md", "# Integrations\n\nUse environment variables for credentials.\n")

    def _ai_agents(self, root: Path) -> None:
        _write(root / "agents" / "orchestrator.py", "class Orchestrator:\n    guardrails = True\n")
        _write(root / "tools" / "README.md", "# Tools\n\nAll tools require guardrails and audit logs.\n")

    def _generic(self, root: Path) -> None:
        for entity in _entities(self.blueprint):
            _write(root / "src" / f"{_safe_name(entity)}.txt", f"Entity: {entity}\n")
        _write(root / "tests" / "test_scaffold.txt", "scaffold tests\n")


class BackendGeneratorFactory:
    @staticmethod
    def get_validator(backend_stack: str, backend_path: str):
        return BackendValidator(stack_id=backend_stack, backend_path=backend_path)

    @staticmethod
    def get_generator(stack_id: str, blueprint: Any, output_path: str):
        return ScaffoldBackendGenerator(stack_id=stack_id, blueprint=blueprint, output_path=output_path)
