import { Server, Globe, Palette, Box, Cpu, Shield, Database, Zap, Layers, Lock, GitBranch, TestTube, MessageSquare, BookOpen, Wifi, Lightbulb, Rocket } from "lucide-react";
import type { CreatePageConfig } from "@/components/create/StackCreateForm";

const STACK_CONFIGS: Record<string, CreatePageConfig> = {
  spring_boot: {
    id: "spring_boot",
    name: "Spring Boot",
    description: "Enterprise Java com ecossistema Spring completo — produção, segurança e governança.",
    icon: Server,
    gradient: "from-emerald-500 to-cyan-500",
    maturity: { score: 93, level: "enterprise" },
    versionLabel: "Versão",
    versionOptions: [
      { value: "17", label: "Java 17" },
      { value: "21", label: "Java 21" },
    ],
    sections: [
      { title: "Build Tool", icon: Box, options: [
        { value: "Maven", label: "Maven", description: "Build clássico maduro" },
        { value: "Gradle", label: "Gradle", description: "Build moderno rápido" },
      ]},
      { title: "Arquitetura", icon: Layers, options: [
        { value: "Monolithic", label: "Monolítica", description: "Menos complexidade" },
        { value: "Microservices", label: "Microsserviços", description: "Escala independente" },
        { value: "Hexagonal", label: "Hexagonal", description: "Ports & Adapters" },
      ]},
      { title: "Recursos", icon: Cpu, options: [
        { value: "Spring Web", label: "Spring Web REST" },
        { value: "Spring Data JPA", label: "JPA + Hibernate" },
        { value: "Spring Security", label: "Segurança" },
        { value: "Eureka", label: "Service Discovery" },
        { value: "Spring Cloud Gateway", label: "API Gateway" },
        { value: "Config Server", label: "Config Centralizada" },
        { value: "Actuator", label: "Monitoramento" },
        { value: "OpenAPI", label: "Swagger / OpenAPI" },
        { value: "Keycloak", label: "Keycloak SSO" },
      ], multiple: true },
      { title: "Mensageria", icon: MessageSquare, options: [
        { value: "Kafka", label: "Apache Kafka" },
        { value: "RabbitMQ", label: "RabbitMQ" },
        { value: "Redis", label: "Redis Pub/Sub" },
        { value: "None", label: "Nenhum" },
      ]},
      { title: "Segurança", icon: Shield, options: [
        { value: "JWT", label: "JWT" },
        { value: "OAuth2", label: "OAuth2" },
        { value: "Keycloak", label: "Keycloak" },
        { value: "Spring Security", label: "Spring Security" },
      ], multiple: true },
      { title: "Banco de Dados", icon: Database, options: [
        { value: "PostgreSQL", label: "PostgreSQL" },
        { value: "MySQL", label: "MySQL" },
        { value: "H2", label: "H2 (Dev/Test)" },
      ]},
      { title: "Testes", icon: TestTube, options: [
        { value: "JUnit", label: "JUnit 5" },
        { value: "Mockito", label: "Mockito" },
        { value: "Testcontainers", label: "Testcontainers" },
      ], multiple: true },
      { title: "Frontend", icon: Globe, options: [
        { value: "Angular", label: "Angular" },
        { value: "React", label: "React" },
        { value: "Vue", label: "Vue" },
        { value: "Thymeleaf", label: "Thymeleaf" },
      ]},
    ],
    recommendedFrontend: ["Angular", "React"],
    forbiddenTerms: ["FastAPI", "Pydantic", "Uvicorn", "SQLAlchemy", "Laravel Sanctum", "Blazor"],
    architecturePreview: [
      { label: "Angular / React", type: "frontend" },
      { label: "API Gateway (Spring Cloud)", type: "gateway" },
      { label: "Microserviços / Monolito", type: "backend" },
      { label: "PostgreSQL", type: "database" },
      { label: "Redis Cache", type: "cache" },
    ],
    projectStructure: [
      "src/main/java/com/.../controller/",
      "src/main/java/com/.../service/",
      "src/main/java/com/.../repository/",
      "src/main/java/com/.../config/",
      "src/main/java/com/.../security/",
      "src/main/resources/application.yml",
      "src/main/resources/db/migration/",
      "Dockerfile",
      "docker-compose.yml",
      "pom.xml",
    ],
    compatibleBackends: ["Spring Boot"],
    frontendCompatibility: ["Angular", "React", "Vue"],
    avoid: ["PHP Monolith", "SQLite alta carga"],
    aiInsights: [
      "Spring Boot é ideal para sistemas corporativos com alta governança.",
      "Keycloak + OAuth2 oferece SSO enterprise robusto.",
      "Microsserviços com Spring Cloud Gateway escala horizontalmente.",
      "Actuator + Prometheus para observabilidade em produção.",
      "Testcontainers viabiliza testes de integração reais.",
    ],
    willGenerate: [
      "Spring Boot 3.x",
      "Maven / Gradle",
      "JPA + Hibernate",
      "Spring Security",
      "OpenAPI / Swagger",
      "Docker + Compose",
      "CI/CD Pipeline",
    ],
    features: [
      { name: "Spring Web REST", icon: Wifi, description: "APIs RESTful com controllers e validação automática", impact: "core" },
      { name: "Spring Data JPA", icon: Database, description: "Acesso a dados com JPA, Hibernate e queries nativas", impact: "core" },
      { name: "Spring Security", icon: Shield, description: "Autenticação e autorização com filtros de segurança", impact: "high" },
      { name: "Cloud Gateway", icon: Zap, description: "API Gateway com roteamento e rate limiting", impact: "high" },
      { name: "Keycloak SSO", icon: Lock, description: "Single Sign-On federado com gerenciamento de identidades", impact: "enterprise" },
      { name: "Config Server", icon: Layers, description: "Configuração centralizada para ambientes distribuídos", impact: "enterprise" },
    ],
  },

  fastapi: {
    id: "fastapi",
    name: "FastAPI",
    description: "APIs assíncronas modernas com alta performance e tipagem forte.",
    icon: Server,
    gradient: "from-cyan-500 to-blue-500",
    maturity: { score: 87, level: "stable" },
    versionLabel: "Versão",
    versionOptions: [
      { value: "3.10", label: "Python 3.10" },
      { value: "3.11", label: "Python 3.11" },
      { value: "3.12", label: "Python 3.12" },
    ],
    sections: [
      { title: "Arquitetura", icon: Layers, options: [
        { value: "Monolithic", label: "Monolítica" },
        { value: "Microservices", label: "Microsserviços" },
      ]},
      { title: "Recursos", icon: Cpu, options: [
        { value: "SQLAlchemy", label: "SQLAlchemy ORM" },
        { value: "SQLModel", label: "SQLModel" },
        { value: "Alembic", label: "Alembic (Migrations)" },
        { value: "Celery", label: "Celery" },
        { value: "RQ", label: "Redis Queue" },
        { value: "Redis", label: "Redis Cache" },
        { value: "OpenAPI", label: "OpenAPI Nativo" },
      ], multiple: true },
      { title: "Mensageria", icon: MessageSquare, options: [
        { value: "Kafka", label: "Kafka" },
        { value: "RabbitMQ", label: "RabbitMQ" },
        { value: "None", label: "Nenhum" },
      ]},
      { title: "Segurança", icon: Shield, options: [
        { value: "JWT", label: "JWT" },
        { value: "OAuth2", label: "OAuth2" },
      ], multiple: true },
      { title: "Banco de Dados", icon: Database, options: [
        { value: "SQLite", label: "SQLite (Dev)" },
        { value: "PostgreSQL", label: "PostgreSQL" },
        { value: "MySQL", label: "MySQL" },
      ]},
      { title: "Testes", icon: TestTube, options: [
        { value: "Pytest", label: "Pytest" },
        { value: "httpx", label: "httpx / TestClient" },
      ], multiple: true },
      { title: "Frontend", icon: Globe, options: [
        { value: "React", label: "React" },
        { value: "Next.js", label: "Next.js" },
        { value: "Vue", label: "Vue" },
      ]},
    ],
    recommendedFrontend: ["React", "Next.js", "Vue"],
    forbiddenTerms: ["Spring Security", "Eureka", "Maven", "Gradle", "Laravel Blade"],
    architecturePreview: [
      { label: "React / Next.js", type: "frontend" },
      { label: "FastAPI Async", type: "backend" },
      { label: "Celery Workers", type: "worker" },
      { label: "PostgreSQL", type: "database" },
      { label: "Redis", type: "cache" },
    ],
    projectStructure: [
      "app/routes/",
      "app/models/",
      "app/schemas/",
      "app/services/",
      "app/core/security/",
      "alembic/",
      "Dockerfile",
      "docker-compose.yml",
      "requirements.txt",
    ],
    compatibleBackends: ["FastAPI"],
    frontendCompatibility: ["React", "Next.js", "Vue"],
    avoid: ["Spring Boot", "Java EE"],
    aiInsights: [
      "FastAPI gera docs OpenAPI automaticamente com Swagger UI e ReDoc.",
      "Async endpoints com async/await maximiza throughput simultâneo.",
      "Pydantic v2 valida dados com performance C nativa.",
      "Celery + Redis desacopla tarefas pesadas da API.",
      "SQLAlchemy + Alembic gerencia migrations de forma robusta.",
    ],
    willGenerate: [
      "FastAPI + Python 3.12",
      "SQLAlchemy + Alembic",
      "Pydantic Schemas",
      "JWT Auth",
      "OpenAPI Docs",
      "Docker + Compose",
      "Async Worker Setup",
    ],
    features: [
      { name: "Async Endpoints", icon: Zap, description: "Requisições concorrentes com async/await nativo", impact: "core" },
      { name: "OpenAPI Auto", icon: BookOpen, description: "Documentação Swagger gerada automaticamente", impact: "core" },
      { name: "Pydantic v2", icon: Shield, description: "Validação de dados em C com erros descritivos", impact: "high" },
      { name: "SQLAlchemy Async", icon: Database, description: "ORM assíncrono com pool de conexões", impact: "high" },
      { name: "Celery Tasks", icon: Cpu, description: "Processamento em background com workers distribuídos", impact: "enterprise" },
      { name: "WebSocket", icon: Wifi, description: "Comunicação bidirecional em tempo real", impact: "high" },
    ],
  },

  nestjs: {
    id: "nestjs",
    name: "NestJS",
    description: "Node enterprise com arquitetura modular, DI forte e TypeScript nativo.",
    icon: Server,
    gradient: "from-red-500 to-rose-500",
    maturity: { score: 85, level: "stable" },
    versionLabel: "Versão",
    versionOptions: [
      { value: "18", label: "Node 18" },
      { value: "20", label: "Node 20" },
      { value: "22", label: "Node 22" },
    ],
    sections: [
      { title: "Recursos", icon: Cpu, options: [
        { value: "TypeScript", label: "TypeScript" },
        { value: "Prisma", label: "Prisma ORM" },
        { value: "TypeORM", label: "TypeORM" },
        { value: "Guards", label: "Guards" },
        { value: "Pipes", label: "Pipes" },
        { value: "Interceptors", label: "Interceptors" },
        { value: "Swagger", label: "Swagger" },
      ], multiple: true },
      { title: "Mensageria", icon: MessageSquare, options: [
        { value: "Kafka", label: "Kafka" },
        { value: "RabbitMQ", label: "RabbitMQ" },
        { value: "None", label: "Nenhum" },
      ]},
      { title: "Segurança", icon: Shield, options: [
        { value: "JWT", label: "JWT" },
        { value: "Passport", label: "Passport" },
      ], multiple: true },
      { title: "Banco de Dados", icon: Database, options: [
        { value: "PostgreSQL", label: "PostgreSQL" },
        { value: "MySQL", label: "MySQL" },
        { value: "MongoDB", label: "MongoDB" },
      ]},
      { title: "Testes", icon: TestTube, options: [
        { value: "Jest", label: "Jest" },
        { value: "Supertest", label: "Supertest" },
      ], multiple: true },
      { title: "Frontend", icon: Globe, options: [
        { value: "Angular", label: "Angular" },
        { value: "React", label: "React" },
        { value: "Next.js", label: "Next.js" },
      ]},
    ],
    recommendedFrontend: ["Angular", "React", "Next.js"],
    forbiddenTerms: ["Pom.xml", "requirements.txt", "Spring", "FastAPI", "Laravel"],
    architecturePreview: [
      { label: "Angular / React", type: "frontend" },
      { label: "NestJS API", type: "backend" },
      { label: "Prisma / TypeORM", type: "database" },
      { label: "Redis / Kafka", type: "cache" },
      { label: "Docker", type: "deploy" },
    ],
    projectStructure: [
      "src/modules/*/",
      "src/common/guards/",
      "src/common/pipes/",
      "src/common/interceptors/",
      "src/config/",
      "prisma/schema.prisma",
      "Dockerfile",
      "docker-compose.yml",
      "package.json",
    ],
    compatibleBackends: ["NestJS"],
    frontendCompatibility: ["Angular", "React", "Next.js"],
    avoid: ["PHP", "C# Monolith"],
    aiInsights: [
      "NestJS modulariza por domínio com módulos, services e controllers.",
      "Guards + Pipes protegem rotas e validam dados automaticamente.",
      "TypeORM + Prisma oferecem ORM flexível para qualquer banco.",
      "Swagger gera documentação automática com decorators.",
      "Kafka + Redis para mensageria desacoplada e escalável.",
    ],
    willGenerate: [
      "NestJS + TypeScript",
      "Prisma / TypeORM",
      "JWT Guards",
      "Swagger Docs",
      "Modular Structure",
      "Docker + Compose",
      "Test Setup",
    ],
    features: [
      { name: "Modular DI", icon: Layers, description: "Injeção de dependência com módulos por domínio", impact: "core" },
      { name: "Guards/Pipes", icon: Shield, description: "Proteção de rotas e validação declarativa", impact: "high" },
      { name: "TypeORM", icon: Database, description: "ORM completo com migrations e relations", impact: "high" },
      { name: "Swagger", icon: BookOpen, description: "Documentação automática com @Api decorators", impact: "core" },
      { name: "Prisma", icon: Database, description: "ORM moderno com type-safety nativo", impact: "high" },
      { name: "Microservices", icon: GitBranch, description: "Arquitetura distribuída com transporte plugável", impact: "enterprise" },
    ],
  },

  express: {
    id: "express",
    name: "Express",
    description: "API pragmática e leve com middleware flexível e baixa fricção.",
    icon: Server,
    gradient: "from-slate-500 to-zinc-400",
    maturity: { score: 74, level: "stable" },
    versionLabel: "Versão",
    versionOptions: [
      { value: "18", label: "Node 18" },
      { value: "20", label: "Node 20" },
    ],
    sections: [
      { title: "Recursos", icon: Cpu, options: [
        { value: "TypeScript", label: "TypeScript (Opcional)" },
        { value: "Prisma", label: "Prisma" },
        { value: "Sequelize", label: "Sequelize" },
        { value: "Mongoose", label: "Mongoose (MongoDB)" },
        { value: "Security Middleware", label: "Security Middleware" },
        { value: "Swagger UI", label: "Swagger UI" },
      ], multiple: true },
      { title: "Segurança", icon: Shield, options: [
        { value: "JWT", label: "JWT" },
        { value: "Passport", label: "Passport" },
      ], multiple: true },
      { title: "Banco de Dados", icon: Database, options: [
        { value: "PostgreSQL", label: "PostgreSQL" },
        { value: "MySQL", label: "MySQL" },
        { value: "MongoDB", label: "MongoDB" },
      ]},
      { title: "Testes", icon: TestTube, options: [
        { value: "Jest", label: "Jest" },
        { value: "Supertest", label: "Supertest" },
      ], multiple: true },
      { title: "Frontend", icon: Globe, options: [
        { value: "React", label: "React" },
        { value: "Vue", label: "Vue" },
        { value: "Next.js", label: "Next.js" },
      ]},
    ],
    recommendedFrontend: ["React", "Vue", "Next.js"],
    forbiddenTerms: ["Pom.xml", "requirements.txt", "Spring", "NestJS", "Laravel"],
    architecturePreview: [
      { label: "React / Vue", type: "frontend" },
      { label: "Express API", type: "backend" },
      { label: "PostgreSQL / Mongo", type: "database" },
      { label: "Redis", type: "cache" },
    ],
    projectStructure: [
      "src/routes/",
      "src/middleware/",
      "src/models/",
      "src/controllers/",
      "src/config/",
      "Dockerfile",
      "docker-compose.yml",
      "package.json",
    ],
    compatibleBackends: ["Express"],
    frontendCompatibility: ["React", "Vue", "Next.js"],
    avoid: ["Keycloak", "Kafka", "Microsserviços complexos"],
    aiInsights: [
      "Express com middleware chain permite pipeline HTTP flexível.",
      "Prisma + PostgreSQL oferece type-safety e auto-complete.",
      "Mongoose simplifica modelagem em projetos MongoDB.",
      "JWT + Passport para autenticação modular.",
      "Ideal para MVPs e APIs de médio porte.",
    ],
    willGenerate: [
      "Express + Node 20",
      "Prisma / Mongoose",
      "JWT Auth",
      "Security Middleware",
      "Swagger Docs",
      "Docker + Compose",
      "Test Suite",
    ],
    features: [
      { name: "Middleware Chain", icon: Zap, description: "Pipeline HTTP flexível com middleware plugável", impact: "core" },
      { name: "Prisma ORM", icon: Database, description: "ORM type-safe com migrations automáticas", impact: "high" },
      { name: "JWT Auth", icon: Lock, description: "Autenticação stateless com tokens JWT", impact: "core" },
      { name: "Swagger UI", icon: BookOpen, description: "Documentação interativa da API", impact: "medium" },
      { name: "Mongoose ODM", icon: Database, description: "Modelagem elegante para MongoDB", impact: "medium" },
    ],
  },

  laravel: {
    id: "laravel",
    name: "Laravel",
    description: "Fullstack PHP produtivo com blade, inertia e ecossistema rico.",
    icon: Server,
    gradient: "from-orange-500 to-red-500",
    maturity: { score: 79, level: "stable" },
    versionLabel: "Versão",
    versionOptions: [
      { value: "8.2", label: "PHP 8.2" },
      { value: "8.3", label: "PHP 8.3" },
    ],
    sections: [
      { title: "Recursos", icon: Cpu, options: [
        { value: "Eloquent", label: "Eloquent ORM" },
        { value: "Migrations", label: "Migrations" },
        { value: "Form Requests", label: "Form Requests" },
        { value: "Policies/Gates", label: "Policies / Gates" },
        { value: "Queues", label: "Queues" },
        { value: "Events", label: "Events" },
        { value: "Scheduler", label: "Scheduler" },
      ], multiple: true },
      { title: "Segurança", icon: Shield, options: [
        { value: "Sanctum", label: "Sanctum" },
        { value: "Passport", label: "Passport" },
      ]},
      { title: "Banco de Dados", icon: Database, options: [
        { value: "MySQL", label: "MySQL" },
        { value: "PostgreSQL", label: "PostgreSQL" },
        { value: "SQLite", label: "SQLite (Dev)" },
      ]},
      { title: "Testes", icon: TestTube, options: [
        { value: "Pest", label: "Pest" },
        { value: "PHPUnit", label: "PHPUnit" },
      ]},
      { title: "Frontend", icon: Globe, options: [
        { value: "Blade", label: "Blade" },
        { value: "Vue", label: "Vue" },
        { value: "React", label: "React" },
        { value: "Inertia", label: "Inertia" },
      ]},
    ],
    recommendedFrontend: ["Blade", "Vue", "React", "Inertia"],
    forbiddenTerms: ["Pom.xml", "requirements.txt", "package.json", "Spring", "FastAPI", "NestJS"],
    architecturePreview: [
      { label: "Blade / Vue", type: "frontend" },
      { label: "Laravel API", type: "backend" },
      { label: "Eloquent ORM", type: "database" },
      { label: "Redis / Queue", type: "cache" },
    ],
    projectStructure: [
      "app/Http/Controllers/",
      "app/Models/",
      "app/Services/",
      "resources/views/",
      "routes/web.php",
      "routes/api.php",
      "database/migrations/",
      "Dockerfile",
      "docker-compose.yml",
    ],
    compatibleBackends: ["Laravel"],
    frontendCompatibility: ["Blade", "Vue", "React", "Inertia"],
    avoid: ["Spring Boot", "FastAPI", "Microsserviços"],
    aiInsights: [
      "Eloquent ORM simplifica queries complexas com relationships.",
      "Sanctum oferece SPA authentication e token API simples.",
      "Artisan CLI gera código e gerencia migrations.",
      "Inertia.js une Laravel + Vue sem construir API separada.",
      "Laravel Horizon gerencia filas Redis com dashboard.",
    ],
    willGenerate: [
      "Laravel 11",
      "Eloquent ORM",
      "Blade / Inertia",
      "Sanctum Auth",
      "Migrations",
      "Docker + Compose",
      "Queue Setup",
    ],
    features: [
      { name: "Eloquent ORM", icon: Database, description: "ORM intuitivo com relationships e eager loading", impact: "core" },
      { name: "Blade Templating", icon: Palette, description: "Template engine elegante com herança de layouts", impact: "core" },
      { name: "Sanctum", icon: Lock, description: "Autenticação SPA e API tokens simplificada", impact: "high" },
      { name: "Artisan CLI", icon: Zap, description: "Linha de comando poderosa para geração de código", impact: "high" },
      { name: "Horizon", icon: Cpu, description: "Dashboard para gerenciamento de filas Redis", impact: "enterprise" },
      { name: "Inertia.js", icon: Globe, description: "Monolito moderno sem API separada", impact: "high" },
    ],
  },

  dotnet: {
    id: "dotnet",
    name: "ASP.NET Core",
    description: "Plataforma Microsoft para aplicações enterprise robustas.",
    icon: Server,
    gradient: "from-violet-500 to-indigo-500",
    maturity: { score: 86, level: "stable" },
    versionLabel: "Versão",
    versionOptions: [
      { value: "7.0", label: ".NET 7.0" },
      { value: "8.0", label: ".NET 8.0" },
    ],
    sections: [
      { title: "Arquitetura", icon: Layers, options: [
        { value: "Web API", label: "Web API" },
        { value: "Minimal API", label: "Minimal API" },
        { value: "Controllers", label: "Controllers" },
      ]},
      { title: "Recursos", icon: Cpu, options: [
        { value: "EF Core", label: "EF Core" },
        { value: "Identity", label: "Identity" },
        { value: "MediatR", label: "MediatR" },
        { value: "SignalR", label: "SignalR" },
        { value: "Swagger", label: "Swagger" },
      ], multiple: true },
      { title: "Segurança", icon: Shield, options: [
        { value: "Identity", label: "Identity" },
        { value: "JWT", label: "JWT" },
      ], multiple: true },
      { title: "Banco de Dados", icon: Database, options: [
        { value: "SQL Server", label: "SQL Server" },
        { value: "PostgreSQL", label: "PostgreSQL" },
        { value: "SQLite", label: "SQLite (Dev)" },
      ]},
      { title: "Testes", icon: TestTube, options: [
        { value: "xUnit", label: "xUnit" },
        { value: "NUnit", label: "NUnit" },
        { value: "Moq", label: "Moq" },
      ], multiple: true },
      { title: "Frontend", icon: Globe, options: [
        { value: "Blazor", label: "Blazor" },
        { value: "Angular", label: "Angular" },
        { value: "React", label: "React" },
      ]},
    ],
    recommendedFrontend: ["Blazor", "Angular", "React"],
    forbiddenTerms: ["Pom.xml", "requirements.txt", "package.json", "Spring", "FastAPI", "NestJS", "Laravel"],
    architecturePreview: [
      { label: "Blazor / Angular", type: "frontend" },
      { label: "ASP.NET Core API", type: "backend" },
      { label: "EF Core", type: "database" },
      { label: "SignalR", type: "realtime" },
      { label: "SQL Server", type: "database" },
    ],
    projectStructure: [
      "Controllers/",
      "Models/",
      "Services/",
      "Data/Migrations/",
      "Hubs/",
      "Program.cs",
      "appsettings.json",
      "Dockerfile",
      "docker-compose.yml",
    ],
    compatibleBackends: ["ASP.NET Core"],
    frontendCompatibility: ["Blazor", "Angular", "React"],
    avoid: ["Java", "PHP", "Node.js"],
    aiInsights: [
      "EF Core abstrai banco com LINQ queries type-safe.",
      "SignalR permite real-time bidirecional para dashboards.",
      "Identity + JWT para autenticação modular e segura.",
      "Minimal APIs reduzem boilerplate para endpoints simples.",
      "Blazor WebAssembly executa C# direto no navegador.",
    ],
    willGenerate: [
      "ASP.NET Core 8",
      "EF Core + Migrations",
      "Identity / JWT",
      "Swagger Docs",
      "SignalR Hub",
      "Docker + Compose",
      "Unit Tests",
    ],
    features: [
      { name: "EF Core", icon: Database, description: "ORM completo com LINQ, migrations e providers", impact: "core" },
      { name: "SignalR", icon: Wifi, description: "Comunicação real-time bidirecional via WebSocket", impact: "high" },
      { name: "Identity", icon: Shield, description: "Sistema de identidade completo com roles", impact: "high" },
      { name: "Minimal APIs", icon: Zap, description: "APIs enxutas sem controllers tradicionais", impact: "core" },
      { name: "Blazor", icon: Globe, description: "Frontend C# com WebAssembly ou Server", impact: "enterprise" },
      { name: "MediatR", icon: GitBranch, description: "Padrão CQRS com mediação de comandos", impact: "enterprise" },
    ],
  },

  "static-site": {
    id: "static-site",
    name: "Static Site",
    description: "HTML/CSS/JS puro — site rápido, sem backend, SEO-first.",
    icon: Globe,
    gradient: "from-sky-500 to-teal-400",
    maturity: { score: 84, level: "stable" },
    versionLabel: "Versão",
    versionOptions: [
      { value: "HTML5", label: "HTML5" },
    ],
    sections: [
      { title: "Recursos", icon: Layers, options: [
        { value: "SEO", label: "SEO" },
        { value: "UX/UI", label: "UX/UI" },
        { value: "Acessibilidade", label: "Acessibilidade" },
        { value: "Formulário", label: "Formulário de contato" },
        { value: "Newsletter", label: "Newsletter" },
        { value: "Analytics", label: "Analytics" },
        { value: "Performance", label: "Performance" },
        { value: "Animações", label: "Animações" },
        { value: "Segurança Frontend", label: "Segurança Frontend" },
      ], multiple: true },
    ],
    hasBackend: false,
    forbiddenTerms: ["Pom.xml", "requirements.txt", "package.json", "Spring", "FastAPI", "backend", "JWT"],
    architecturePreview: [
      { label: "HTML/CSS/JS", type: "frontend" },
      { label: "CDN / Static Host", type: "deploy" },
    ],
    projectStructure: [
      "index.html",
      "assets/css/",
      "assets/js/",
      "assets/img/",
      "pages/",
      "components/",
      ".htaccess / nginx.conf",
    ],
    frontendCompatibility: [],
    avoid: ["Backend", "JWT"],
    aiInsights: [
      "Ideal para landing pages e sites institucionais.",
      "Performance máxima com HTML/CSS puro sem frameworks.",
      "CDN deployment garante carregamento global rápido.",
      "Sem dependências de backend reduz custos de infra.",
      "SEO-first com meta tags e structured data.",
    ],
    willGenerate: [
      "HTML5 + CSS3",
      "SEO Otimizado",
      "Responsivo",
      "Performance Otimizada",
      ".htaccess / nginx",
      "Analytics Ready",
    ],
    features: [
      { name: "SEO Optimized", icon: Globe, description: "Meta tags, Open Graph e structured data", impact: "core" },
      { name: "Performance", icon: Zap, description: "Carregamento rápido sem frameworks pesados", impact: "core" },
      { name: "Responsivo", icon: Palette, description: "Layout adaptável para todos dispositivos", impact: "core" },
      { name: "Analytics", icon: Cpu, description: "Google Analytics / Plausible integrado", impact: "medium" },
    ],
  },

  angular: {
    id: "angular",
    name: "Angular",
    description: "Enterprise Frontend Platform — SPA com TypeScript, RxJS e módulos poderosos.",
    icon: Palette,
    gradient: "from-red-500 to-pink-500",
    maturity: { score: 91, level: "enterprise" },
    versionLabel: "Versão",
    versionOptions: [
      { value: "17.x", label: "Angular 17" },
      { value: "18.x", label: "Angular 18" },
    ],
    sections: [
      { title: "Recursos", icon: Cpu, options: [
        { value: "RxJS", label: "RxJS Reactive State" },
        { value: "Routing", label: "Lazy Loading Routes" },
        { value: "Services", label: "Services + DI" },
        { value: "Guards", label: "Route Guards" },
        { value: "Interceptors", label: "HTTP Interceptors" },
        { value: "Reactive Forms", label: "Reactive Forms" },
        { value: "API Client", label: "HTTP Client" },
        { value: "Auth Integration", label: "Auth Integration" },
      ], multiple: true },
    ],
    hasBackend: false,
    recommendedFrontend: ["Spring Boot", "NestJS", "FastAPI"],
    architecturePreview: [
      { label: "Angular SPA", type: "frontend" },
      { label: "API Gateway", type: "gateway" },
      { label: "Spring / NestJS", type: "backend" },
      { label: "PostgreSQL", type: "database" },
      { label: "Redis", type: "cache" },
    ],
    projectStructure: [
      "src/app/components/",
      "src/app/pages/",
      "src/app/services/",
      "src/app/guards/",
      "src/app/interceptors/",
      "src/app/shared/",
      "src/assets/",
      "angular.json",
      "Dockerfile",
      "nginx.conf",
    ],
    frontendCompatibility: ["All major frameworks"],
    compatibleBackends: ["Spring Boot", "NestJS", "FastAPI"],
    avoid: ["Blazor", "PHP monolith"],
    aiInsights: [
      "Angular é ideal para dashboards enterprise e painéis administrativos.",
      "RxJS e observable streams gerenciam estado reativo complexo.",
      "Guards protegem rotas com RBAC e lazy loading.",
      "Reactive Forms com validação declarativa escalam bem.",
      "Angular CLI gera components, services e modules rapidamente.",
    ],
    willGenerate: [
      "Angular 18",
      "RxJS + Services",
      "Lazy Loading Routes",
      "JWT Guards",
      "HTTP Interceptors",
      "Docker + Nginx",
      "Tailwind CSS",
    ],
    features: [
      { name: "Reactive Forms", icon: Zap, description: "Formulários enterprise escaláveis com validação", impact: "core" },
      { name: "RxJS Streams", icon: Wifi, description: "Programação reativa com observable pipelines", impact: "high" },
      { name: "Route Guards", icon: Shield, description: "Proteção de rotas com RBAC e autenticação", impact: "high" },
      { name: "Lazy Loading", icon: Layers, description: "Carregamento sob demanda de módulos e rotas", impact: "core" },
      { name: "Angular CLI", icon: Zap, description: "Geração de código e scaffolding automático", impact: "core" },
      { name: "SSR (Angular Universal)", icon: Globe, description: "Server-side rendering para SEO e performance", impact: "enterprise" },
    ],
  },

  react: {
    id: "react",
    name: "React",
    description: "Biblioteca moderna para interfaces reativas e componentizadas.",
    icon: Palette,
    gradient: "from-sky-500 to-cyan-500",
    maturity: { score: 87, level: "stable" },
    versionLabel: "Versão",
    versionOptions: [
      { value: "18.x", label: "React 18" },
    ],
    sections: [
      { title: "Recursos", icon: Cpu, options: [
        { value: "Vite", label: "Vite (recomendado)" },
        { value: "CRA", label: "Create React App" },
        { value: "Router", label: "React Router" },
        { value: "Hooks", label: "Hooks" },
        { value: "Context", label: "Context API" },
        { value: "Zustand", label: "Zustand State" },
        { value: "API Client", label: "API Client" },
        { value: "Forms", label: "Forms" },
      ], multiple: true },
    ],
    hasBackend: false,
    recommendedFrontend: ["FastAPI", "Express", "Spring Boot", "NestJS"],
    architecturePreview: [
      { label: "React SPA", type: "frontend" },
      { label: "BFF / API Layer", type: "gateway" },
      { label: "FastAPI / Express", type: "backend" },
      { label: "PostgreSQL", type: "database" },
    ],
    projectStructure: [
      "src/components/",
      "src/pages/",
      "src/hooks/",
      "src/context/",
      "src/services/",
      "src/utils/",
      "public/",
      "Dockerfile",
      "nginx.conf",
      "vite.config.ts",
    ],
    frontendCompatibility: ["All backends"],
    compatibleBackends: ["FastAPI", "Express", "Spring Boot", "NestJS", "Laravel"],
    avoid: ["Blazor", "ASP.NET WebForms"],
    aiInsights: [
      "React com Vite oferece HMR extremamente rápido em desenvolvimento.",
      "Zustand + Context API gerenciam estado sem bibliotecas pesadas.",
      "React Router v6 com loaders e actions para data fetching.",
      "Hooks personalizados encapsulam lógica de negócio reutilizável.",
      "Ecosystem maduro com milhares de componentes e ferramentas.",
    ],
    willGenerate: [
      "React 18 + Vite",
      "React Router v6",
      "Zustand / Context",
      "API Client (axios)",
      "Auth Integration",
      "Docker + Nginx",
      "Tailwind CSS",
    ],
    features: [
      { name: "Vite HMR", icon: Zap, description: "Hot Module Replacement instantâneo", impact: "core" },
      { name: "React Router", icon: GitBranch, description: "Roteamento SPA com loaders e actions", impact: "core" },
      { name: "Zustand", icon: Cpu, description: "State management leve e performático", impact: "high" },
      { name: "Hooks", icon: Layers, description: "Lógica reutilizável com hooks personalizados", impact: "core" },
      { name: "React Query", icon: Database, description: "Data fetching e cache inteligente", impact: "high" },
      { name: "Tailwind CSS", icon: Palette, description: "Estilização utilitária com design system", impact: "medium" },
    ],
  },

  nextjs: {
    id: "nextjs",
    name: "Next.js",
    description: "React fullstack com SSR, SSG, server actions e SEO otimizado.",
    icon: Palette,
    gradient: "from-gray-500 to-stone-500",
    maturity: { score: 86, level: "stable" },
    versionLabel: "Versão",
    versionOptions: [
      { value: "13.x", label: "Next 13 (Pages)" },
      { value: "14.x", label: "Next 14 (App Router)" },
    ],
    sections: [
      { title: "Recursos", icon: Cpu, options: [
        { value: "App Router", label: "App Router" },
        { value: "API Routes", label: "API Routes" },
        { value: "SSR/SSG", label: "SSR / SSG" },
        { value: "SEO", label: "SEO" },
        { value: "Auth", label: "Auth" },
        { value: "Server Actions", label: "Server Actions" },
      ], multiple: true },
    ],
    hasBackend: false,
    recommendedFrontend: ["FastAPI", "NestJS", "Spring Boot"],
    architecturePreview: [
      { label: "Next.js App", type: "frontend" },
      { label: "API Routes / BFF", type: "gateway" },
      { label: "FastAPI / NestJS", type: "backend" },
      { label: "PostgreSQL", type: "database" },
    ],
    projectStructure: [
      "app/(routes)/",
      "app/api/",
      "components/",
      "lib/",
      "styles/",
      "public/",
      "next.config.js",
      "Dockerfile",
      "docker-compose.yml",
    ],
    frontendCompatibility: ["All backends"],
    compatibleBackends: ["FastAPI", "NestJS", "Spring Boot"],
    avoid: ["PHP", "Legacy MVC"],
    aiInsights: [
      "Next.js App Router unifica rotas, layouts e loading states.",
      "Server Components reduzem JavaScript enviado ao cliente.",
      "Server Actions executam lógica backend sem API explícita.",
      "SSG + ISR combinam performance com conteúdo dinâmico.",
      "API Routes eliminam necessidade de BFF separado.",
    ],
    willGenerate: [
      "Next.js 14 + App Router",
      "Server Components",
      "Server Actions",
      "SEO Optimized",
      "Auth Integration",
      "Docker + Compose",
      "Tailwind CSS",
    ],
    features: [
      { name: "App Router", icon: GitBranch, description: "Roteamento baseado em pastas com layouts aninhados", impact: "core" },
      { name: "Server Components", icon: Cpu, description: "Componentes renderizados no servidor sem JS client", impact: "core" },
      { name: "Server Actions", icon: Zap, description: "Mutações diretas sem API routes", impact: "high" },
      { name: "SSG + ISR", icon: Globe, description: "Static generation com revalidação incremental", impact: "high" },
      { name: "SEO", icon: Shield, description: "Meta tags, sitemap e robots automáticos", impact: "high" },
      { name: "Middleware", icon: Layers, description: "Edge middleware para redirects e proteção", impact: "enterprise" },
    ],
  },

  vue: {
    id: "vue",
    name: "Vue",
    description: "Framework progressivo com Pinia, Vue Router e composição elegante.",
    icon: Palette,
    gradient: "from-emerald-400 to-green-600",
    maturity: { score: 83, level: "stable" },
    versionLabel: "Versão",
    versionOptions: [
      { value: "3.x", label: "Vue 3" },
    ],
    sections: [
      { title: "Recursos", icon: Cpu, options: [
        { value: "Pinia", label: "Pinia State" },
        { value: "Vue Router", label: "Vue Router" },
        { value: "API Client", label: "API Client" },
        { value: "Forms", label: "Forms" },
        { value: "Composition API", label: "Composition API" },
      ], multiple: true },
    ],
    hasBackend: false,
    recommendedFrontend: ["Laravel", "FastAPI", "Express"],
    architecturePreview: [
      { label: "Vue SPA", type: "frontend" },
      { label: "API Layer", type: "gateway" },
      { label: "Laravel / FastAPI", type: "backend" },
      { label: "PostgreSQL", type: "database" },
    ],
    projectStructure: [
      "src/components/",
      "src/views/",
      "src/stores/",
      "src/router/",
      "src/composables/",
      "src/services/",
      "public/",
      "Dockerfile",
      "nginx.conf",
    ],
    frontendCompatibility: ["All backends"],
    compatibleBackends: ["Laravel", "FastAPI", "Express", "Spring Boot"],
    avoid: ["ASP.NET WebForms"],
    aiInsights: [
      "Vue 3 Composition API organiza lógica por função, não por opção.",
      "Pinia é o state manager oficial com suporte TypeScript nativo.",
      "Vue Router com lazy loading otimiza bundle inicial.",
      "Ecossistema Vue cresce rapidamente com Nuxt, Vite e Pinia.",
      "Curva de aprendizado suave ideal para times pequenos.",
    ],
    willGenerate: [
      "Vue 3 + Composition API",
      "Pinia State",
      "Vue Router",
      "API Client",
      "Auth Integration",
      "Docker + Nginx",
      "Tailwind CSS",
    ],
    features: [
      { name: "Composition API", icon: Layers, description: "Lógica organizada por função com composables", impact: "core" },
      { name: "Pinia", icon: Cpu, description: "State management oficial com DevTools", impact: "high" },
      { name: "Vue Router", icon: GitBranch, description: "Roteamento SPA com guards e lazy loading", impact: "core" },
      { name: "Vite", icon: Zap, description: "Build tool rápida com HMR instantâneo", impact: "core" },
      { name: "Nuxt SSR", icon: Globe, description: "Server-side rendering para SEO (via Nuxt)", impact: "enterprise" },
    ],
  },

  blazor: {
    id: "blazor",
    name: "Blazor",
    description: "Frontend C# com WebAssembly ou Server, integração nativa .NET.",
    icon: Palette,
    gradient: "from-violet-500 to-purple-700",
    maturity: { score: 75, level: "stable" },
    versionLabel: "Versão",
    versionOptions: [
      { value: "8.0", label: ".NET 8.0" },
    ],
    sections: [
      { title: "Recursos", icon: Cpu, options: [
        { value: "Blazor Server", label: "Blazor Server" },
        { value: "Blazor WebAssembly", label: "Blazor WebAssembly" },
        { value: "Auth Integration", label: "Auth Integration" },
        { value: "API Client", label: "API Client" },
      ], multiple: true },
    ],
    hasBackend: false,
    recommendedFrontend: ["ASP.NET Core"],
    architecturePreview: [
      { label: "Blazor UI", type: "frontend" },
      { label: "ASP.NET Core API", type: "backend" },
      { label: "EF Core + SQL", type: "database" },
    ],
    projectStructure: [
      "Pages/",
      "Components/",
      "Services/",
      "Shared/",
      "wwwroot/",
      "Program.cs",
      "Dockerfile",
    ],
    frontendCompatibility: ["ASP.NET Core"],
    compatibleBackends: ["ASP.NET Core"],
    avoid: ["Java", "JavaScript frameworks"],
    aiInsights: [
      "Blazor WebAssembly executa C# compilado direto no navegador.",
      "Blazor Server mantém conexão SignalR com UI reativa.",
      "Compartilha models e validação entre client e server.",
      "RenderTree diffs UI eficientemente sem DOM virtual.",
      "Integração nativa com Visual Studio e ecossistema .NET.",
    ],
    willGenerate: [
      "Blazor (.NET 8)",
      "C# Components",
      "Auth Integration",
      "API Client",
      "Docker + Compose",
      "EF Core Setup",
    ],
    features: [
      { name: "WebAssembly", icon: Globe, description: "Executa C# no navegador sem plugins", impact: "core" },
      { name: "Server Mode", icon: Wifi, description: "Conexão SignalR com UI reativa em tempo real", impact: "core" },
      { name: "Shared Code", icon: Layers, description: "Models e validação compartilhados client/server", impact: "high" },
      { name: "Razor Syntax", icon: Zap, description: "Templates HTML com C# embutido", impact: "core" },
    ],
  },
};

export default STACK_CONFIGS;
